# Generated by Django 5.0.7 on 2024-07-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('home_title', models.CharField(max_length=255)),
                ('cv_file', models.CharField(max_length=255)),
                ('about_title', models.CharField(max_length=255)),
                ('about_description', models.TextField()),
                ('about_photo', models.CharField(max_length=255)),
                ('services_title', models.CharField(max_length=255)),
                ('services_subtitle', models.CharField(max_length=255)),
                ('services_description', models.TextField()),
                ('start_time', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
