# Generated by Django 5.0.7 on 2024-07-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='about_photo',
            field=models.ImageField(upload_to='about_photos/'),
        ),
        migrations.AlterField(
            model_name='config',
            name='cv_file',
            field=models.FileField(upload_to='cv_files/'),
        ),
    ]
