# Generated by Django 5.0.7 on 2024-07-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_config_about_photo_alter_config_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='home_bg_photo',
            field=models.ImageField(blank=True, null=True, upload_to='home_bg__photos/'),
        ),
    ]
