# Generated by Django 5.0.7 on 2024-07-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_alter_config_home_bg_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='home_bg_photo',
            field=models.ImageField(blank=True, null=True, upload_to='home_bg_photos/'),
        ),
    ]
